### ISSUE TITLE
Actualización canales

### ISSUE THREAD

**Issue by gbertu** [TSCNEO/ListaDeCanales#1]
Hola @TSCNEO , veo que se debería actualizar la lista de canales, ya que Sorys ha publicado listas nuevas. He intentado subir la actualización para colaborar, pero no tengo permisos para poder contribuir.

Estaría encantado en ayudar a mantener actualizada la lista, y así evitar hacer un fork para eso.

Un saludo,

**Comment by TSCNEO** [comment]
Muchas gracias por tu disposición. Lamentablemente ya no dispongo del tiempo necesario para mantener semana a semana el repositorio actualizado. 
Puedes hacer un fork, actualizarlo y después hacerme un pull request para que una tus cambios. 

Un saludo

**Comment by gbertu** [comment]
Ok, pues así lo haré! ;)
